docs/source/topics.rst, goblet/cli.py, goblet/client.py, goblet/config.py, goblet/deploy.py, goblet/utils.py
--only-function flag for `goblet deploy`
`config.json` to configure cloudfunction
=> config.json and --only-function

.github/workflows/main.yml, Makefile, dev-requirements.txt, goblet/resources/routes.py, goblet/resources/scheduler.py, goblet/tests/test_scheduler.py
=> add pytest github action

.gitignore, README.md, docs/source/index.rst, docs/source/topics.rst, examples/main.py, goblet/__version__.py, goblet/cli.py, goblet/decorators.py, goblet/handler.py, goblet/resources/routes.py, goblet/resources/scheduler.py, goblet/tests/test_app.py, goblet/tests/test_openapispec.py, requirements.txt, setup.py
* custom schema types using marshmallow
* use type hints for openapi params
* support for splitting routes into multiple files
* improved logging for scheduler deployment (#18 )
=> openapi schema enhancements

.github/workflows/main.yml, .gitignore, README.md, docs/source/index.rst, docs/source/quickstart.rst, docs/source/resources.rst, docs/source/topics.rst, examples/main.py, goblet/__version__.py, goblet/cli.py, goblet/client.py, goblet/decorators.py, goblet/deploy.py, goblet/resources/pubsub.py, goblet/resources/routes.py, goblet/resources/scheduler.py, goblet/tests/test_pubsub.py, requirements.txt, setup.py
* PubSub support
```
@app.topic('test')
def topic(data):
app.log.info(data)
return 
```
* python 3.8 testing 
* can set default project using gcloud
* reorganized documentation
* a few minor bug fixes
=> PubSub Resource 

docs/source/topics.rst, goblet/resources/routes.py, goblet/tests/test_openapispec.py
request body works with openapispec2 (closes #30)
add support for formData which allows for file uploads in openapispec 2
=> Bugfix for RequestBody and formData

goblet/__version__.py, goblet/resources/routes.py
route address being passed to open api spec incorrectly
=> Bugfix- route address being passed to open api spec incorrectly

goblet/resources/routes.py
Added delay for deleting nested config resources (closes #23)
=> Bugfix - Increase delay for deleting nested config resources

goblet/__version__.py
=> Release 0.4.4

docs/source/index.rst, docs/source/quickstart.rst, goblet/__version__.py, goblet/app.py, goblet/client.py, goblet/config.py, goblet/decorators.py, goblet/deploy.py, goblet/handler.py, goblet/resources/http.py, goblet/resources/pubsub.py, goblet/resources/routes.py, goblet/resources/scheduler.py, goblet/resources/storage.py, goblet/test_utils.py, goblet/tests/test_deployer.py, goblet/tests/test_pubsub.py, goblet/tests/test_routes.py, goblet/tests/test_scheduler.py, goblet/utils.py
* Adding Docstrings (closes #53 )
* Removed some unused code (`region`, `project_hash`)
=> Docstrings 

goblet/test_utils.py, goblet/tests/test_http.py, goblet/tests/test_pubsub.py, goblet/tests/test_routes.py, goblet/tests/test_scheduler.py, goblet/tests/test_storage.py
Tests now use imported `dummy_function` and `mock_dummy_function`
Remove unnecessary monkeypatches
=> [Tests] Cleanup Tests

README.md, docs/source/blogs.rst, docs/source/examples.rst, docs/source/index.rst, docs/source/topics.rst, examples/main.py, goblet/__version__.py, goblet/resources/routes.py, goblet/tests/test_openapispec.py
* supports routes with custom backends (closes #48) . 
```
@app.route('/custom_backend', backend="https://www.CLOUDRUN_URL.com/home")    
def home():        
return 
```
* added examples, blogs to docs
=> Custom Backends

goblet/__version__.py, goblet/resources/http.py
=> [Http]- http header bugfix

docs/source/topics.rst, examples/main.py, goblet/__version__.py, goblet/cli.py, goblet/resources/routes.py, goblet/tests/test_openapispec.py
Adding ability to add security definition at the method level 
```
@app.route('/method_security', security=[{"your_custom_auth_id": []}])
def method_security():
return
```
=> Method security

goblet/app.py
* set local logger to `werkzeug` to work with functions framework
=> [Local] Fix Logger

README.md, docs/source/quickstart.rst, examples/main.py, goblet/__init__.py, goblet/__version__.py, goblet/app.py, goblet/deploy.py
adds helper to set entrypoint. `add_entrypoint` (addresses #88 )
```
from goblet import Goblet, jsonify, Response, add_entrypoint
app = Goblet(function_name="goblet-test-issue", local="test")
add_entrypoint(app)
@app.http()
def main(request):
app.log.info("triggered")
return jsonify(request.json)
```
=> add_entrypoint

docs/source/resources.rst, goblet/__version__.py, goblet/decorators.py, goblet/resources/scheduler.py, goblet/tests/test_scheduler.py
add scheduler support for `retryConfig` , `attemptDeadline`, `name` (closes #93 )
=> Scheduler Enhancements

docs/source/integrations.rst, goblet/decorators.py, goblet/resources/storage.py, goblet/tests/test_storage.py
Custom storage cloudfunction name
=> [Storage] Fix name

docs/source/quickstart.rst, docs/source/topics.rst, examples/main.py, goblet/__version__.py, goblet/app.py, goblet/cli.py, goblet/utils.py
*Set local default to "local", so default command will be `goblet local`. (closes #80 )
=> [CLI] Simplify local command

goblet/deploy.py
Add `test` and `venv` directories to be excluded in `zib_directory` function
=> Add `test` and `venv` directories to be excluded in `zib_directory` function

docs/source/topics.rst
* Add documentation for service account authentication and jwt generation (#113 )
=> Documentation for service account auth

.flake8, .github/workflows/main.yml, goblet/__version__.py, goblet/app.py, goblet/cli.py, goblet/client.py, goblet/common_cloud_actions.py, goblet/config.py, goblet/decorators.py, goblet/deploy.py, goblet/handler.py, goblet/resources/http.py, goblet/resources/pubsub.py, goblet/resources/routes.py, goblet/resources/scheduler.py, goblet/resources/storage.py, goblet/test_utils.py, goblet/tests/test_app.py, goblet/tests/test_config.py, goblet/tests/test_deployer.py, goblet/tests/test_http.py, goblet/tests/test_openapispec.py, goblet/tests/test_pubsub.py, goblet/tests/test_routes.py, goblet/tests/test_scheduler.py, goblet/tests/test_storage.py, goblet/tests/test_utils.py, goblet/utils.py, goblet/write_files.py
Add Black formatter (closes #107 )
=> Black formatter

docs/source/topics.rst, goblet/resources/routes.py, goblet/tests/test_openapispec.py
right now got it working with one query. Need to make it work with multiple query parameters
=> add query support for goblet openspec generation

docs/source/topics.rst, goblet/__version__.py, goblet/decorators.py, goblet/tests/test_pubsub.py
* Surfaces request context (closes #129)
```
@app.topic("TOPIC")
def context():
context = app.request_context
return "context"
```
=> [Goblet] Request Context

goblet/app.py, goblet/client.py, goblet/common_cloud_actions.py, goblet/decorators.py, goblet/deploy.py, goblet/handler.py, goblet/resources/http.py, goblet/resources/pubsub.py, goblet/resources/routes.py, goblet/resources/scheduler.py, goblet/resources/storage.py, goblet/tests/test_app.py, goblet/tests/test_deployer.py
* Added `VersionedClients` class that contains the base api clients defined. (closes #138)
* Added `client_versions` argument to Goblet to allow for specifying specific client api versions. 
* Updated `Handler` init
=> Refactor Clients

docs/source/topics.rst
* Documentation of secret manager integration for cloudrun and cloudfunction (v1) (closes #58 )
=> [Documentation] Secrets Manager Integration

docs/source/resources.rst, goblet/__version__.py, goblet/common_cloud_actions.py, goblet/decorators.py, goblet/deploy.py, goblet/handler.py, goblet/resources/http.py, goblet/resources/pubsub.py, goblet/resources/routes.py, goblet/resources/storage.py, goblet/tests/data/http/pubsub-deploy-cross-project/get-v1-operations-cHJlbWlzZS1nb3Zlcm5hbmNlLXJkL3VzLWNlbnRyYWwxL2dvYmxldC10b3BpYy1jcm9zcy1wcm9qZWN0L1l5bEE5cTZMdk1j_1.json, goblet/tests/data/http/pubsub-deploy-cross-project/get-v1-projects-goblet-locations-us-central1-functions-goblet-topic-cross-project_1.json, goblet/tests/data/http/pubsub-deploy-cross-project/post-v1-projects-goblet-locations-us-central1-functions-generateUploadUrl_1.json, goblet/tests/data/http/pubsub-deploy-cross-project/post-v1-projects-goblet-locations-us-central1-functions_1.json, goblet/tests/data/http/pubsub-deploy-cross-project/put-v1-projects-goblet-subscriptions-goblet-topic-cross-project-test_1.json, goblet/tests/test_pubsub.py, requirements.txt
Allow for cross-project subscriptions to be made as well as the option to use a subscription vs a pubsub trigger (closes #140).
```
@app.topic('test', project="CROSS_PROJECT")
def cross_project(data):
return 
@app.topic('test', use_subscription=True)
def subsciption(data):
return 
```
=> Cross project subscription

docs/source/backends.rst, docs/source/topics.rst, goblet/cli.py, goblet/write_files.py
* update docs related to cloudrun backend (closes #143 )
* fix typos in cli.py
* update goblet init `main.py`
=> Fix docs related to #143

goblet/common_cloud_actions.py, goblet/resources/pubsub.py, goblet/tests/data/http/pubsub-update-subscription/get-v1-projects-goblet-locations-us-central1-functions-test-cross-project_1.json, goblet/tests/data/http/pubsub-update-subscription/patch-v1-projects-goblet-subscriptions-test-cross-project-test_1.json, goblet/tests/data/http/pubsub-update-subscription/put-v1-projects-goblet-subscriptions-test-cross-project-test_1.json, goblet/tests/test_pubsub.py
* Fixes subscription update (closes #145 )
* Fixes subscription destroy
=> [Pubsub] Fix subscription update and destroy

goblet/decorators.py, goblet/resources/pubsub.py, goblet/tests/test_app.py, goblet/tests/test_http.py, goblet/tests/test_pubsub.py, goblet/tests/test_routes.py
* Pubsub events from a subscription do not have a context like regular triggers so needed to add logic to determine subscription from request (closes #147 )
=> [Pubsub] Cross subscription correctly triggers

goblet/decorators.py, goblet/resources/pubsub.py
* Sync correctly skips resources that have not been enabled (closes #156 )
* Fix pubsub return for subscriptions
=> [Sync] Fix resource permission issue

README.md, docs/source/quickstart.rst, docs/source/resources.rst
* Update docs for testing scheduler locally (closes #155 )
=> [Docs] Test scheduler locally

.github/workflows/main.yml, requirements.txt, setup.py
* Bump versions in requirements.txt
* Add tests for python 3.10 (closes #154 )
=> Update Requirements, Tests for python 3.10

goblet/__version__.py, goblet/decorators.py
Fixes 400 error when get_json() is being called for requests with no json (closes #152 )
=> Bugfix: Add is_json check

goblet/__version__.py, goblet/decorators.py, goblet/resources/routes.py, goblet/tests/test_pubsub.py
* Addresses 400 error with http get requests happening
* Fix api gateway update
=> Bugfix-json headers, gateway update

goblet/__version__.py, goblet/decorators.py
order was causing errors (closes #166 )
=> Bugfix json error 2

.github/workflows/main.yml, README.md, docs/source/integrations.rst, goblet/cli.py, goblet/client.py, goblet/deploy.py, goblet/tests/test_deployer.py, goblet/write_files.py, setup.py
* specify gcloud version for cloudrun deploys (closes #150)
`client_versions={"gcloud":"alpha"}`
* pass in list of args to cloudrun deploys 
```
"cloudrun": {
"execution-environment": "gen2",
"update-env-vars":["ENV1=val1","ENV2=val2"],
}   
```
=> Add gcloud config for cloudrun deployments

README.md
Update readme to include Cloud Run
=> Update readme to include Cloud Run

goblet/deploy.py, goblet/resources/pubsub.py, goblet/resources/storage.py, goblet/utils.py
Uses python version of deployment environment instead of hardcoded python37 (closes #188)
=> [Cloudfunction] uses python runtime

goblet/cli.py, goblet/resources/pubsub.py, goblet/tests/test_pubsub.py
Return a pubsub response if possible, otherwise return 200 (closes #187).
=> [Pubsub] Return Response

goblet/deploy.py, goblet/resources/pubsub.py, goblet/tests/test_pubsub.py
=> Bugfix: Subscription attribute filter 

goblet/backends/backend.py, goblet/common_cloud_actions.py, goblet/resources/routes.py, goblet/tests/data/http/deployer-cloudrun-artifact/get-v2-projects-goblet-locations-us-central1-operations-cdea49e3-fe97-45cd-99a2-144712d747f2_1.json, goblet/tests/data/http/deployer-cloudrun-artifact/post-v2-projects-goblet-locations-us-central1-services_1.json, goblet/tests/data/http/deployer-cloudrun-deploy/post-v2-projects-goblet-locations-us-central1-services_1.json, goblet/tests/data/http/routes-destroy/get-v1-projects-goblet-locations-global-operations-operation-1618942401498-5c06b66c0cd62-daa1d904-3a7a1626_1.json, goblet/tests/data/http/routes-destroy/get-v1-projects-goblet-locations-us-central1-operations-operation-1618942343806-5c06b63507fcf-e953e836-bac7096a_1.json
* Add waiters for api gateway destroy functions (closes #201)
=> Add waiters for api gateway destroy

goblet/client.py, goblet/common_cloud_actions.py
Pass through cloudbuild timeout to the cloudbuild `wait_for_operation`
=> Cloudbuild Timeout

goblet/resources/routes.py, goblet/tests/test_openapispec.py, goblet/tests/test_routes.py
* ability to pass through deadline value in `"x-google-backend"` (closes #224 )
=> Gateway timeout

goblet/client.py
refresh google application default credentials before sending http requests
=> refresh auth credentials

CONTRIBUTING.md, README.md, docs/source/backends.rst, docs/source/blogs.rst, docs/source/resources.rst, examples/main.py, goblet/__version__.py, goblet/backends/cloudrun.py, goblet/cli.py, goblet/client.py, goblet/common_cloud_actions.py, goblet/decorators.py, goblet/resources/jobs.py, goblet/resources/scheduler.py, goblet/revision.py, goblet/tests/data/http/job-deploy-schedule/get-v1-operations-build-goblet-NjgzYTU4ZGEtNGRlMi00OWY3LTg3ZGEtOTg0OGNmMDA2ZDQy_1.json, goblet/tests/data/http/job-deploy-schedule/get-v1-projects-goblet-builds-683a58da-4de2-49f7-87da-9848cf006d42_1.json, goblet/tests/data/http/job-deploy-schedule/get-v1-projects-goblet-builds_1.json, goblet/tests/data/http/job-deploy-schedule/get-v2-projects-goblet-locations-us-central1-services-goblet-test_1.json, goblet/tests/data/http/job-deploy-schedule/post-apis-run.googleapis.com-v1-namespaces-goblet-jobs_1.json, goblet/tests/data/http/job-deploy-schedule/post-v1-projects-goblet-builds_1.json, goblet/tests/data/http/job-deploy-schedule/post-v1-projects-goblet-locations-us-central1-jobs_1.json, goblet/tests/data/http/job-deploy-schedule/post-v2beta-projects-goblet-locations-us-central1-functions-generateUploadUrl_1.json, goblet/tests/data/http/job-deploy/get-v1-projects-goblet-builds-e0e8f281-4344-4d4c-8a0e-a9f474068fd0_1.json, goblet/tests/data/http/job-deploy/get-v1-projects-goblet-builds_1.json, goblet/tests/data/http/job-deploy/post-apis-run.googleapis.com-v1-namespaces-goblet-jobs_1.json, goblet/tests/data/http/job-destroy/delete-apis-run.googleapis.com-v1-namespaces-goblet-jobs-goblet-test-test_1.json, goblet/tests/data/http/job-sync/delete-apis-run.googleapis.com-v1-namespaces-goblet-jobs-test-job-test_1.json, goblet/tests/data/http/job-sync/get-apis-run.googleapis.com-v1-namespaces-goblet-jobs_1.json, goblet/tests/test_jobs.py
closes #176 
```
@app.job("job1", schedule="* * * * *")
def job1_task1(id):
app.log.info(f"job...{id}")
return "200"
@app.job("job1", task_id=1)
def job1_task2(id):
app.log.info(f"different task for job...{id}")
return "200"
```
=> Cloudrun jobs

goblet/common_cloud_actions.py
* Handle missing artifact and raise helpful info (closes #232 )
=> MissingArtifact exception

goblet/cli.py
* Running goblet deploy in cicd return successful even if exception is raises. It should exit on exception instead
=> Add exit 1 codes to cli

docs/source/topics.rst, goblet/cli.py
* pass in custom port to goblet local (closes #243 )
```
goblet local -p 5000 
```
=> [CLI] goblet local custom port

docs/source/topics.rst, goblet/__version__.py
=> Add private python library example to docs

goblet/resources/plugins/pydantic.py, goblet/tests/test_openapispec.py
=> Support duplicate nested Pydantic models

docs/source/topics.rst, goblet/app.py, goblet/backends/cloudfunctionv1.py, goblet/backends/cloudfunctionv2.py, goblet/config.py, goblet/infrastructures/redis.py, goblet/infrastructures/vpcconnector.py, goblet/resources/eventarc.py, goblet/resources/jobs.py, goblet/resources/pubsub.py, goblet/resources/routes.py, goblet/resources/storage.py, goblet/revision.py, goblet/tests/test_config.py
Labels can be added to all resources that support labels by passing in a labels dictionary to `Goblet` app. You can also 
specify labels in `config.json` under the key label. (closes #239 )
```
app = Goblet(function_name="example-job",  labels={"sample_label":"sample_value"})
```
config.json 
```
{
"labels":{"sample_label_2":"2"},
"stages":{
"test": {
"labels": {
"sample_label_stage":"staged"
}
}
}
}
```
=> Add label for resources that support it

docs/source/topics.rst
Update docs on how to reference secrets in secret manager as environment variables in cloudrun.
=> update cloudrun secrets documentation

docs/source/topics.rst, goblet/decorators.py, goblet/tests/test_app.py
Bugfix for `stages` argument in stage decorator. 
Added tests
=> Fix for stages argument in stage decorator

goblet/backends/backend.py, goblet/infrastructures/vpcconnector.py
- update req body to read `ipCidrRange` from vpc connector config
- remove `labels` from connector creation, key is not supported
- add `.goblet/config.json` to backend zip files
=> [vpcconnector] resource creation fixes

goblet/common_cloud_actions.py
=> Bugfix pubsub update

goblet/backends/cloudrun.py
* Add caching to cloudbuild (closes #334 )
=> [Cloudbuild] Caching

docs/source/topics.rst, examples/example_multi_functions/config.json, goblet/backends/backend.py, goblet/backends/cloudrun.py
support multiple dockerfiles (closes #335 )
```
{
"stages": {
"func1": {
"function_name": "func1",
"dockerfile": "func1.dockerfile",
"main_file" : "func1.py",
"requirements_file": "func1_requirements.txt"
},
"func2": {
"function_name": "func2",
"dockerfile": "func2.dockerfile",
"main_file" : "func2.py",
"requirements_file": "func2_requirements.txt"
}
}
}
```
=> Multiple Dockerfile support

goblet/tests/test_redis.py, requirements.txt
* Update goblet-gcp-client to 0.1.5
* Update redis update test
=> Fix redis update test

docs/source/conf.py, docs/source/handlers.rst, docs/source/topics.rst
* add documentation for testing handlers locally (closes #276 , #363 )
=> [Docs] - Local handler examples

docs/source/topics.rst, goblet/__version__.py, goblet/app.py, goblet/backends/backend.py, goblet/cli.py, goblet/client.py, goblet/common_cloud_actions.py, goblet/config.py, goblet/decorators.py, goblet/handlers/bq_remote_function.py, goblet/handlers/cloudtasktarget.py, goblet/handlers/eventarc.py, goblet/handlers/handler.py, goblet/handlers/jobs.py, goblet/handlers/pubsub.py, goblet/handlers/routes.py, goblet/handlers/scheduler.py, goblet/handlers/storage.py, goblet/infrastructures/alerts.py, goblet/infrastructures/apigateway.py, goblet/infrastructures/cloudtask.py, goblet/infrastructures/redis.py, goblet/infrastructures/vpcconnector.py, goblet/resource_manager.py, goblet/revision.py
* Ability to specify log level via ENV variable or via CLI. 
* Package now prints files being zipped using debug flag (closes #373 )
=> [CLI] Debug logging

requirements.txt
update goblet-gcp-client to 0.1.6
=> Update goblet-gcp-client version

goblet/backends/cloudrun.py
Get and set env vars from job container closes #333
=> [Local] Get and set env vars from job container

docs/source/conf.py
=> Add jquery to sphinx

.gitignore, examples/example_api_gateway_security_definitions/config.json, examples/example_api_gateway_security_definitions/main.py
add example_api_gateway_security_definitions to examples (closes #381)
=> Add example_api_gateway_security_definitions

goblet/write_files.py
- 404 file not found error is currently returned
=> update doc link for readme generated during goblet init

goblet/backends/cloudfunctionv1.py, goblet/backends/cloudfunctionv2.py
=> update required apis

goblet/backends/cloudfunctionv1.py, goblet/backends/cloudfunctionv2.py, goblet/backends/cloudrun.py
=> Update missing permissions

goblet/__version__.py, goblet/handlers/scheduler.py
=> Bugfix 415 - Fix scheduler service account

goblet/handlers/eventarc.py, goblet/tests/test_eventarc.py, requirements.txt, setup.py
add `event_data_content_type` flag for eventarc
update protobuf version
=> Eventarc event_data_content_type support

docs/source/backends.rst, docs/source/topics.rst, goblet.schema.json, goblet/backends/cloudfunctionv2.py, goblet/backends/cloudrun.py, goblet/common_cloud_actions.py, goblet/handlers/pubsub.py, goblet/handlers/routes.py, goblet/handlers/storage.py, goblet/revision.py, goblet/tests/data/http/storage-deploy-cloudfunctionv2/get-v2-projects-goblet-locations-us-central1-operations-operation-1694828915033-605701b6f85bd-9f637ec5-b4801dd4_1.json, goblet/tests/data/http/storage-deploy-cloudfunctionv2/post-v2-projects-goblet-locations-us-central1-functions-generateUploadUrl_1.json, goblet/tests/data/http/storage-deploy-cloudfunctionv2/post-v2-projects-goblet-locations-us-central1-functions_1.json, goblet/tests/test_apigateway.py, goblet/tests/test_backend.py, goblet/tests/test_deployer.py, goblet/tests/test_storage.py, utils/schema/README.md, utils/schema/base.json, utils/schema/build.py, utils/schema/references/apigateway.v1.json, utils/schema/references/cloudbuild.v1.json, utils/schema/references/cloudfunctions.v1.json, utils/schema/references/cloudfunctions.v2.json, utils/schema/references/cloudtasks.v2.json, utils/schema/references/redis.v1.json, utils/schema/references/run.v2.json, utils/schema/references/vpcaccess.v1.json
documentation on building json schema file
breaking changes:
- explicit difference in configuration keys `cloudfunction` and `cloudfunction_v2`
- move `artifact_tag` and `artifact_registry` from `cloudbuild` key to `deploy` key
=> JSON Schema File for code-completion of .goblet/config.json

docs/source/backends.rst, goblet/backends/cloudrun.py, goblet/revision.py, goblet/tests/data/http/build-tags/get-v1-operations-build-goblet-OTRjYzMxYzEtYTkyNC00ZWIxLWI5OWUtOTg3MjMxNWQyOTFj_1.json, goblet/tests/data/http/build-tags/get-v1-projects-goblet-builds_1.json, goblet/tests/data/http/build-tags/get-v1-projects-goblet-locations-us-central1-repositories-cloud-run-source-deploy_1.json, goblet/tests/data/http/build-tags/get-v1-projects-goblet_1.json, goblet/tests/data/http/build-tags/get-v1-projects-goblet_2.json, goblet/tests/data/http/build-tags/get-v2-projects-goblet-locations-us-central1-operations-8182fff8-6fc8-4964-8866-12c196371e80_1.json, goblet/tests/data/http/build-tags/post-v1-projects-goblet-builds_1.json, goblet/tests/data/http/build-tags/post-v2-projects-goblet-locations-us-central1-services_1.json, goblet/tests/data/http/build-tags/post-v2beta-projects-goblet-locations-us-central1-functions-generateUploadUrl_1.json, goblet/tests/test_deployer.py
solves https://github.com/goblet/goblet/issues/433 and https://github.com/goblet/goblet/issues/432
=> Add support for custom tags and GOBLET_ARTIFACT_TAG env var

.flake8, docs/source/topics.rst, examples/main.py, goblet/decorators.py, goblet/errors.py, goblet/handlers/routes.py, goblet/resource_manager.py, goblet/response.py, goblet/tests/test_app.py
Use the `errorhandler` decorator to handle errors based on its exception class. By default `GobletRouteNotFoundError` is handled by returning a 404 response code.
```
@app.errorhandler("GobletRouteNotFoundError")
def handle_missing_route(error):
return Response("Custom Error", status_code=404)
@app.errorhandler("ValueError")
def return_error_string(error):
return Response(str(error), status_code=200)
```
=> errorhandler

CONTRIBUTING.md, README.md
Refer to CONTRIBUTING.md in README and add a note on requests-mock package
=> [Docs] Enhance README and CONTRIBUTING files

goblet/app.py
=> specify project_id for StructuredLogHandler to ensure trace is formatted properly

goblet/alerts/__init__.py, goblet/alerts/alerts.py, goblet/app.py, goblet/tests/test_alerts.py
* Add default alert type (#473 )
* Fix alert sync
* Fix duplicate deployment (#474 )
=> Fix sync and default alert type

goblet/cli.py
=> Fix docs url

Makefile
=> Add make format command

goblet/handlers/scheduler.py
=> add try catch block around set iam binding

.github/workflows/main.yml, goblet/__version__.py
=> Add github action job timeout
