- docs/source/topics.rst
With latest changes to `routes` local requests now need require header `X-Envoy-Original-Path`
> Update Docs for Local Routing

- docs/source/topics.rst
- goblet/decorators.py
* Improve `get_event_type` so don't need to add headers for local testing (closes #49 )
* Doc section on local vscode debugging
> Improve get_event_type logic

- docs/source/resources.rst
- examples/main.py
- goblet/decorators.py
- goblet/resources/http.py
- goblet/tests/test_http.py
Adds option to supply headers in the http endpoint to trigger different endpoints based on their headers. (closes #50 )
handles sets which triggers if that header is contained in the request
```
@app.http(headers={"X-GitHub-Event"})
def github(request):
return  issues + prs
```
handles dictionaries which triggers if the header and corresponding value is contained in the request
```
@app.http(headers={"X-GitHub-Event":"issues"})
def issues(request):
return issues
@app.http(headers={"X-GitHub-Event":"pull_requests"})
def prs(request):
return prs
```
> Http Header Filters

- docs/source/topics.rst
- goblet/resources/routes.py
- goblet/tests/test_openapispec.py
* Ability to configure apiSpec using `config.json`, which included gatewayServiceAccount (closes #71)
```
{
"apiConfig": {
"gatewayServiceAccount": "projects/-/serviceAccounts/ServiceAccount@PROJECT",
"labels": {
"label1" : "value1"
}
}
}  
```
* Add security section to openApispec based on securityDefinitions or `security` field in `config.json` (closes #72 )
> apiConfig options and Security Section in OpenApiSpec

- goblet/deploy.py
https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions/generateUploadUrl
requires an empty body
> [Deploy] GCP breaking change with generateUploadUrl

- docs/source/index.rst
- docs/source/resources.rst
- examples/main.py
- goblet/resources/scheduler.py
- goblet/tests/data/http/schedule-deploy-multiple/get-v1-projects-goblet-locations-us-central1-functions-goblet-test-schedule_1.json
- goblet/tests/data/http/schedule-deploy-multiple/post-v1-projects-goblet-locations-us-central1-jobs_1.json
- goblet/tests/data/http/schedule-deploy-multiple/post-v1-projects-goblet-locations-us-central1-jobs_2.json
- goblet/tests/data/http/schedule-deploy-multiple/post-v1-projects-goblet-locations-us-central1-jobs_3.json
- goblet/tests/test_scheduler.py
* multiple schedulers for one entry function
```
@app.schedule('5 * * * *')
@app.schedule('2 * * * *')
def scheduled_function()
app.current_request
return
```
* pass through custom scheduler params such as `body`, `headers`, `httpMethod`
```
@app.schedule('5 * * * *', httpMethod='POST', headers={'X-Custom': 'header'}, body='BASE64 ENCODED STRING')
@app.schedule('5 * * * *', httpMethod='GET', headers={'X-Custom': 'header2'}, body='BASE64 ENCODED STRING 2')
def scheduled_function()
app.current_request
return
```
closes #91
> Scheduler Enhancements

- goblet/decorators.py
set entrypoint to `goblet_entrypoint` instead of app because of #88 (closes #95)
> [Pubsub] Fix entrypoint

- docs/source/topics.rst
- goblet/app.py
- goblet/cli.py
- goblet/deploy.py
- goblet/utils.py
Add `config` entry that allows any file to become the `main.py` file and therefore allow for multiple functions to be deploying using similar code bases. (#90 )
for example with the following files
```
func1.py
func2.py
shared.py
```
we could have the goblet `.config`
```
{
"stages": {
"func1": {
"function_name": "func1",
"main_file" : "func1.py"
},
"func2": {
"function_name": "func2",
"main_file" : "func2.py"
}
}
```
Note this may cause some imports to break if something is importing from the `func1.py` or `func2.py` during runtime.
> Multi Cloudfunction Support

- docs/source/topics.rst
- examples/main.py
- goblet/decorators.py
- goblet/tests/test_app.py
You can trigger custom middleware using the `before_request` and `after_request` decorators. These allow you to trigger custom functions before a request is passed to your request handler or do post processing on your responses. (closes #133 ) 
```
@app.before_request()
def add_db(request):
app.g.db = "db"
return request
@app.after_request(event_type="pubsub")
def add_header(response):
response.headers["X-Custom"] = "custom header"
return response
```
> Add Before and After Middleware handlers

- README.md
- docs/source/resources.rst
- goblet/__version__.py
- goblet/app.py
- goblet/decorators.py
- goblet/resources/routes.py
- goblet/tests/test_routes.py
Allow the option to have apigateway routes or cloudrun routes for the cloudrun backend. For cloudfunctions only api gateway will work with routes. These are accessed via the `routes_type` argument in Goblet. (closes #151 )
```
app = Goblet(function_name="cloudrun-routing", routes_type="cloudrun", backend="cloudrun")
```
> [Routes] cloudrun and apigateway route_type option

- docs/source/topics.rst
- examples/main.py
- examples/requirements.txt
- goblet/__version__.py
- goblet/resources/routes.py
- goblet/tests/test_openapispec.py
Pass in function to `app.handlers["route"].marshmallow_attribute_function` that gets added to the marshmallow openapispec converter plugin
```# Custom Marshmallow Fields
from marshmallow_enum import EnumField
from enum import Enum
def enum_to_properties(self, field, **kwargs):
"""
Add an OpenAPI extension for marshmallow_enum.EnumField instances
"""
if isinstance(field, EnumField):
return {'type': 'string', 'enum': [m.name for m in field.enum]}
return {}
app.handlers["route"].marshmallow_attribute_function = enum_to_properties
class StopLight(Enum):
green = 1
yellow = 2
red = 3
class TrafficStop(Schema):
light_color = EnumField(StopLight)
@app.route("/traffic")
def traffic() -> TrafficStop:
return TrafficStop().dump({"light_color":StopLight.green})
```
> [Openapi] Custom type support

- goblet/__version__.py
- goblet/resources/routes.py
- goblet/tests/test_openapispec.py
Makes operationId's unique per method. (closes #183 )
`"operationId": "get_function_name",`
`"operationId": "post_function_name",`
> [Openapispec] Make operationId unique

- docs/source/topics.rst
- goblet/cli.py
Added option to select --version 3 to also create an openapi 3.0.1 spec (closes #185 ). 
`
goblet openapi FUNCTION -v 3
`
this returns in `.goblet/config.json`
```
FUNCTION_NAME_openapi_spec.yml
FUNCTION_NAME_openapi_spec_3.yml
```
> [OpenAPI] openapi  -v 3 option 

- docs/source/topics.rst
- goblet/resources/routes.py
- goblet/tests/test_routes.py
Setting cors on an endpoint or the application will automatically add an OPTIONS method to support preflighting requests.
> Add preflight cors support

- goblet/deploy.py
- current check defaults flags to `no-allow-unauthenticated` even when `allow-unauthenticated` is set
- removing check because cloud run deploy defaults to requiring authentication when no flag is set
> remove check for authentication flag

- goblet/write_files.py
The CMD in the dockerfile isn't used, so to improve clarity, I think it should be removed. This argument instead is being used.
https://github.com/goblet/goblet/blob/bec9e85dcb66a13834aada9a4d4b99772494f947/goblet/deploy.py#L151
> Removed unused CMD

- goblet/decorators.py
- goblet/resources/scheduler.py
- goblet/tests/test_scheduler.py
- goblet/write_files.py
Timezone is a pretty important part of any schedule - moving it to the function argument should make it clear how to do so.
I saw the kwargs, so I tried `timeZone` (what the API wants) and `time_zone` (what the python scheduler library wants). Had to go through the source code to find out it was `timezone`, so I hope this change makes things easier for other newcomers!
> Include timezone as a schedule argument

- Dockerfile
- goblet/write_files.py
Updates the base container from `python:3.7-slim` to
`python:3.10-slim`
Also, installs the dependencies before copying the
application code to take advantage of docker build layer
caching.
Closes https://github.com/goblet/goblet/issues/205
> chore(Dockerfile): update python 3.7 -> 3.10

- CONTRIBUTING.md
- README.md
- docs/source/resources.rst
- goblet/resources/pubsub.py
- goblet/tests/data/http/pubsub-deploy-subscription-config/get-v1-projects-goblet-locations-us-central1-functions-goblet-topic-subscription-config_1.json
- goblet/tests/data/http/pubsub-deploy-subscription-config/put-v1-projects-goblet-subscriptions-goblet-topic-subscription-config-test_1.json
- goblet/tests/test_pubsub.py
- addresses https://github.com/goblet/goblet/issues/181
- allow pass through configuration for pubsub subscriptions
- note: need to ensure conflicting subscription config values are not set i.e, pushConfig or enableMessageOrdering and enableExactlyOnceDelivery cannot be set at the same time
> [PubSub] pass through configuration for subscriptions

- docs/source/topics.rst
- goblet/backends/backend.py
- goblet/tests/test_backend.py
renamed custom_files. It now has format
```
"custom_files": {
"include": ["*.yaml"],
"exclude": ["*.secret"]
}
```
> Fix custom files

- goblet/revision.py
Restores functionality previously available at: https://github.com/goblet/goblet/blob/e7c95fff858d34b968bb685ff0948c69db989832/goblet/deploy.py#L155
> Default cloud run command

- goblet/resources/routes.py
Utilize the existing `content_types` field to allow users to specify `Content-Type:` header for request data, and add `tags` field to group endpoints under categories in Swagger docs
> Add support for `content_types` and `tags` fields for openapi spec creation

- goblet/common_cloud_actions.py
- goblet/resources/jobs.py
- goblet/revision.py
* simplifies `getCloudbuildArtifact` and explicitly gets the artifact based on registry set during the build (closes #252 )
> Bugfix252-parallel build artifacts

- docs/source/resources.rst
- examples/example_cloudrun_job/config.json
- goblet/__version__.py
- goblet/resources/jobs.py
update cloudrun job example and support `job_metadata` pass through for vpc and networking configurations (closes #260 )
```
{
"function_name":"FUNCTION_NAME",
"job_container": {
"env": [
{
"name": "ENV",
"value": "VALUE"
}
],
"resources": {
"limits": {
"cpu": "4000m",
"memory": "7000Mi"
}
}
},
"job_spec":{
"serviceAccountName": "SA@PROJECT.iam.gserviceaccount.com",
"timeoutSeconds":"600s",
"maxRetries": 1
},
"job_annotations":{
"run.googleapis.com/vpc-access-connector": "projects/PROJECT/locations/LOCATION/connectors/CONNECTION_NAME",
"run.googleapis.com/cloudsql-instances": "projects/PROJECT/locations/LOCATION/connectors/SQL_CONNECTION",
"run.googleapis.com/vpc-access-egress": "private-ranges-only"
},
"scheduler":{
"serviceAccount": "SA_SCHEDULER@PROJECT.iam.gserviceaccount.com"
}
}
```
> Cloudrun jobs metadata

- goblet/app.py
- goblet/cli.py
- requirements.txt
- setup.py
logger should return json structured logs when deployed in gcp. can pass in extra json data using `extra` field in logs
see https://googleapis.dev/python/logging/latest/std-lib-integration.html#logging-json-payloads (closes #159 #264  )
@AdeelK93 let me know if this would work for you
> Add gcloud logger

- goblet/backends/cloudrun.py
I don't know what the correct action is here, is `return 0` correct? Cause it does result in a successful deploy.
Or should a different exception be thrown? Either way, the `KeyError: 'source'` message that gets thrown right now is confusing.
> latest_build_source = resp["builds"][0]["source"]
KeyError: 'source'
What do you think? Thanks!
> latest_build_source KeyError

- docs/source/resources.rst
- goblet/resources/routes.py
- goblet/tests/test_openapispec.py
closes #291 
```
@app.route('/deadline', deadline=10)
def deadline():
return 'custom_deadline'
```
> [Routes] Pass through custom deadline field

- docs/source/topics.rst
- goblet/backends/backend.py
- goblet/backends/cloudfunctionv1.py
- goblet/backends/cloudfunctionv2.py
- goblet/backends/cloudrun.py
- goblet/cli.py
- goblet/tests/test_backend.py
`goblet local --set-env --stage dev` which would set the environment variables in that stage (closes #282 ).
> [Local] Add set-env flag to goblet local command

- Dockerfile
- docs/source/backends.rst
- goblet/backends/cloudrun.py
- goblet/write_files.py
- exposes cloudbuild network to docker build container, will enable access to ADC credentials within cloudbuild steps: https://cloud.google.com/build/docs/build-config-file-schema#network
- adding keyrings to the Dockerfile will handle authentication and allow services to install packages directly from artifact registry: https://cloud.google.com/artifact-registry/docs/python/authentication#keyring (is required to be installed before packages can be installed)
> [cloudrun] enable cloudbuild network for cloudbuild step

- docs/source/topics.rst
- goblet/app.py
- goblet/decorators.py
- goblet/infrastructures/alerts.py
- goblet/infrastructures/infrastructure.py
- goblet/infrastructures/redis.py
- goblet/infrastructures/vpcconnector.py
- goblet/resources/eventarc.py
- goblet/resources/handler.py
- goblet/resources/http.py
- goblet/resources/jobs.py
- goblet/resources/pubsub.py
- goblet/resources/routes.py
- goblet/resources/scheduler.py
- goblet/resources/storage.py
- goblet/tests/test_app.py
- goblet/tests/test_deployer.py
- goblet/tests/test_jobs.py
- goblet/tests/test_pubsub.py
- goblet/tests/test_redis.py
- goblet/tests/test_scheduler.py
- goblet/tests/test_vpcconnector.py
You can limit what resources are deployed by stage by using the stage decorator (closes #247 ). For example, the following will only
be deployed and run when stage is dev.
```
@app.route("/stage/dev")
@app.stage("dev")
def dev() -> str:
return "Only deployed and run when STAGE=dev"
```
Refactors resource registration
> Stage decorator and Resource Registration Refactor

- .github/workflows/main.yml
- dev-requirements.txt
- examples/main.py
- goblet/__version__.py
- goblet/backends/cloudfunctionv1.py
- goblet/backends/cloudrun.py
- goblet/cli.py
- goblet/client.py
- goblet/config.py
- goblet/decorators.py
- goblet/infrastructures/alerts.py
- goblet/infrastructures/vpcconnector.py
- goblet/resources/jobs.py
- goblet/resources/plugins/pydantic.py
- goblet/revision.py
- goblet/tests/data/http/get-secrets/get-v1-projects-goblet-secrets-TESTSECRET-versions-1-access_1.json
- goblet/tests/test_app.py
- goblet/tests/test_backend.py
- goblet/tests/test_routes.py
* local support for `--set-env` secrets (#309 ). Goblet will now get the secret from secrets manager and set as env variable. If permission is not granted, then the secret will be skipped locally. 
* local support for `--set-env` and `stage` for cloudrun jobs (#312 )
> Local support for --set-env secrets

- goblet/__version__.py
- goblet/decorators.py
- goblet/tests/test_app.py
* Correctly pass through current_request and request_context (closes #257 )
```
app = Goblet(function_name="1")
app2  = Goblet(function_name="2")
app = app + app2
@app2.route()
def app2_route():
app2.current_request
```
> Pass through current_request to added api's

- docs/source/topics.rst
- goblet/app.py
- goblet/decorators.py
- goblet/utils.py
- update goblet class to have a `is_sub_app` flag, this is used when combining multiple apps and helps determine which is the main app when deploying
- update goblet `app_list` field to be set on initialization
> sub app enhancements

- goblet/decorators.py
- goblet/tests/test_routes.py
*  Support for list request body(closes #347 )
support request body 
```mock_event1.json = [{"field": "value"}, {"field": "value"}]```
> [Bugfix] Support for list request body

- goblet/handlers/scheduler.py
update scheduler sync to determine job name by splitting on function name instead of `-`
this prevented the sync for recognizing jobs that were created with complex naming such as `function-name-job-name`
> update scheduler sync filtered name check

- .github/workflows/main.yml
- goblet/app.py
- goblet/backends/backend.py
- goblet/backends/cloudfunctionv1.py
- goblet/backends/cloudfunctionv2.py
- goblet/backends/cloudrun.py
- goblet/cli.py
- goblet/client.py
- goblet/common_cloud_actions.py
- goblet/handlers/bq_remote_function.py
- goblet/handlers/eventarc.py
- goblet/handlers/handler.py
- goblet/handlers/jobs.py
- goblet/handlers/pubsub.py
- goblet/handlers/routes.py
- goblet/handlers/scheduler.py
- goblet/handlers/storage.py
- goblet/infrastructures/alerts.py
- goblet/infrastructures/apigateway.py
- goblet/infrastructures/cloudtask.py
- goblet/infrastructures/infrastructure.py
- goblet/infrastructures/redis.py
- goblet/infrastructures/vpcconnector.py
- goblet/tests/data/http/services-check/get-v1-projects-goblet-services-batchGet_1.json
- goblet/tests/data/http/services-enable/get-v1-operations-acat.p2-1234567890-5a312762-427a-499f-8025-ab8150acd344_1.json
- goblet/tests/data/http/services-enable/post-v1-projects-goblet-services-batchEnable_1.json
- goblet/tests/test_services.py
- setup.py
- add cli command for checking and enabling gcp service apis
- closes #218 
- limit flake8 and testing to python versions >= 3.8
> [cli] check or enable gcp service apis

- goblet/cli.py
* The zipfile was not closed in all cases resulting in a corrupted file during `goblet package`. The zipfile is always closed during `goblet deploy` (closes #357 )
> [CLI] Package command correctly closes zipfile

- .github/workflows/main.yml
- goblet/tests/test_vpcconnector.py
- requirements.txt
- enable vpc connector deploy testing
- requires https://github.com/goblet/goblet_gcp_client/pull/13
- closes #307
> update goblet gcp client

- goblet/app.py
- goblet/cli.py
- goblet/handlers/handler.py
- goblet/resource_manager.py
- goblet/tests/data/http/routes-deploy-without-backend/get-v1-projects-goblet-locations-us-central1-functions-goblet-routes_1.json
- goblet/tests/data/http/vpcconnector-deploy-solo/get-v1-projects-goblet-locations-us-central1-connectors-vpc-test_1.json
- goblet/tests/data/http/vpcconnector-deploy-solo/get-v1-projects-goblet-locations-us-central1-operations-ccbd4475-81a7-41cf-abcd-beb8ec7c2d7c_1.json
- goblet/tests/data/http/vpcconnector-deploy-solo/post-v1-projects-goblet-locations-us-central1-connectors_1.json
- goblet/tests/test_apigateway.py
- goblet/tests/test_cloudtasks.py
- goblet/tests/test_deployer.py
- goblet/tests/test_redis.py
- goblet/tests/test_routes.py
- goblet/tests/test_vpcconnector.py
addresses #304 
- **BREAKING**: update `skip-resources` flag to be `skip-handlers`
- add option to deploy, destroy, and sync one or more handler resources with flag `-h / --handler`
- add option to deploy, destroy, and sync one or more infrastructure resources with flag `-i / --infra`
- add flags `skip-backend` and `skip-handlers` to destroy command
- add check to verify backend is deployed if handlers are being deployed
```
goblet deploy -l us-central1 -h jobs -i alerts --skip-backend
goblet sync -l us-central1 -h jobs --skip-infra --skip-backend
goblet destroy -l us-central1 -i alerts --skip-handlers --skip-backend
```
> [cli] add flags to manage specific resources

- goblet/backends/cloudrun.py
Currently within the `CloudRun.create_build()` function, the `self.config.cloudbuild` reference is assigned to the `build_configs` variable. As a result, when `artifact_registry` is removed from the config (`build_configs.pop("artifact_registry", None)`), it becomes unavailable in later deployment steps.
Suggested fix: copy `config.cloudbuild` dict
> Create a local copy of config.cloudbuild instead of assigning a reference in CloudRun.create_build()

- docs/source/infrastructures.rst
- goblet/infrastructures/alerts.py
- gives more flexibility to log matching alerts not tied to a deployed resource within the same app
> [alerts] allow log match condition filter to be replaced instead of concatenated

- goblet/backends/cloudrun.py
in a project with multiple services, the latest cloudbuild may not always reflect the service being deployed, adding a default tag will help filter for checksum hash comparison
> [cloudrun] add default goblet tag to cloudrun build for filtering

- goblet/handlers/plugins/pydantic.py
- goblet/tests/test_openapispec.py
- requirements.txt
- setup.py
closes #391 
- updated import location for ModelMetaclass (now a private class that could be broken in future releases)
- update PydanticSimpleModels to default to None so the field is not required (related change https://docs.pydantic.dev/dev-v2/migration/#required-optional-and-nullable-fields)
- update `schema` function ref to `model_json_schema` (related change https://docs.pydantic.dev/dev-v2/migration/#changes-to-pydanticbasemodel
)
- update field parsing for optional/nullable fields (https://docs.pydantic.dev/dev-v2/migration/#changes-to-json-schema-generation)
- update requirements to latest versions
- added `resolve_schema` function to resolve schema for optional and nullable fields
> [routes] pydantic v2 support

- goblet/config.py
- goblet/tests/test_config.py
GConfig().key1 recursively returns a new GConfig object loaded with the dictionary under key1
Since goblet code expects that most of the output of using GConfig is a dictionary, implemented __eq__, __bool__, __getitem__, __setitem__, get() and keys()
Also subclassed dict to make it JSON Serializable
> upgrade GConfig to handle nested __getattr__

- goblet/handlers/routes.py
- goblet/tests/test_openapispec.py
unpack security_definitions inside goblet.handlers.routes.OpenApiSpec
make securityDefinitions in openapispec tests GConfig instances test write spec to yaml
add test to write securityDefinitions to yaml
> fix issue [Openapispec] - error creating spec #437

- examples/example_multi_container/main.py
- examples/example_pubsub_emulator/main.py
- examples/example_pubsub_topics/main.py
- examples/main.py
- goblet/__version__.py
- goblet/handlers/routes.py
- goblet/tests/test_openapispec.py
closes #442 
```
class StopLight(Enum):
green = 'green'
yellow = 'yellow'
red = 'red'
@app.route("/{color}")
def prim_enum(color: StopLight):
return StopLight(color)
```
returns openapi spec as follows
```
- in: path
name: color
required: true
type: string
enum:
- green
- yellow
- red
```
> Enum Route Param

- goblet.schema.json
- utils/schema/base.json
- utils/schema/references/apigateway.v1.json
- utils/schema/references/cloudbuild.v1.json
- utils/schema/references/cloudfunctions.v1.json
- utils/schema/references/cloudfunctions.v2.json
- utils/schema/references/cloudtasks.v2.json
- utils/schema/references/redis.v1.json
- utils/schema/references/run.v2.json
- utils/schema/references/vpcaccess.v1.json
- json schema was missing the `cloudrun` key that maps to https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services#Service
- script that builds the json schema also updates API definitions to latest.
> add cloudrun mapping in json schema to CloudRun Service config

- setup.py
The pydantic version peg here is a bit strict, and tests pass on newer versions
> Relax pydantic version strictness

- goblet/backends/cloudrun.py
Use lru_cache decorator from func tools to cache the last call and avoid the calls to Cloudrun Admin API with each cloud task execution. closes #458
> [Fix] Cache Cloud Run HTTP Endpoint

- docs/source/topics.rst
- examples/example_bq_spark_stored_procedure/additional.py
- examples/example_bq_spark_stored_procedure/main.py
- examples/example_bq_spark_stored_procedure/spark.py
- examples/main.py
- goblet/__version__.py
- goblet/handlers/routes.py
- goblet/tests/test_routes.py
closes #469 
```
@app.route('/custom_cors', cors=CORSConfig(allow_origin='localhost', allow_methods=["GET"], extra_headers={"X-TEST":"X-HEADER-VALUE"}))
def custom_cors():
return jsonify('localhost is allowed with GET method')
```
> Cors allow methods and custom headers

- goblet/__version__.py
- goblet/backends/backend.py
This closes #483 which occurs when including `config.json` in `custom_files` , would replace config.json, which is modified by goblet behind the scenes if a  stage is specified.
> Bugfix 483 - custom files include

- goblet/handlers/routes.py
- goblet/tests/test_routes.py
This PR checks if there is missing an 3rd argument on Tuples route responses and manage it properly when CORS is enabled. (closes #490 )
> fix: add 3rd arg validation on routes with CORS enabled

- goblet/handlers/pubsub.py
in cases where the topic may contain the service name, limit replacement to first occurrence
```
app = Goblet(function_name="tester")
@app.pubsub_subscription("tester-ingest", use_subscription=True)
```
replacement of service name prefix in sub `tester-tester-ingest` = topic name `ingest`
`ValueError: Topic ingest not found`
> [pubsub] replace first occurrence of goblet service prefix for subscription topic name
